/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FreeToolRouteImport } from './routes/free-tool'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SupplierTokenRouteImport } from './routes/supplier/$token'
import { Route as ResourcesTraceabilityGuideRouteImport } from './routes/resources.traceability-guide'
import { Route as ResourcesEudrOverviewRouteImport } from './routes/resources.eudr-overview'
import { Route as ResourcesEudrChecklistRouteImport } from './routes/resources.eudr-checklist'
import { Route as LegalTermsOfSaleRouteImport } from './routes/legal/terms-of-sale'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalNoticesRouteImport } from './routes/legal/notices'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutOrganizationRouteImport } from './routes/_app/_auth/onboarding/_layout.organization'
import { Route as AppAuthDashboardLayoutShipmentsRouteImport } from './routes/_app/_auth/dashboard/_layout.shipments'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutExportRouteImport } from './routes/_app/_auth/dashboard/_layout.export'
import { Route as AppAuthDashboardLayoutCheckoutRouteImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthDashboardLayoutSettingsBillingRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeToolRoute = FreeToolRouteImport.update({
  id: '/free-tool',
  path: '/free-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SupplierTokenRoute = SupplierTokenRouteImport.update({
  id: '/supplier/$token',
  path: '/supplier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTraceabilityGuideRoute =
  ResourcesTraceabilityGuideRouteImport.update({
    id: '/traceability-guide',
    path: '/traceability-guide',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesEudrOverviewRoute = ResourcesEudrOverviewRouteImport.update({
  id: '/eudr-overview',
  path: '/eudr-overview',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesEudrChecklistRoute = ResourcesEudrChecklistRouteImport.update({
  id: '/eudr-checklist',
  path: '/eudr-checklist',
  getParentRoute: () => ResourcesRoute,
} as any)
const LegalTermsOfSaleRoute = LegalTermsOfSaleRouteImport.update({
  id: '/legal/terms-of-sale',
  path: '/legal/terms-of-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticesRoute = LegalNoticesRouteImport.update({
  id: '/legal/notices',
  path: '/legal/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/login/_layout',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutOrganizationRoute =
  AppAuthOnboardingLayoutOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthDashboardLayoutShipmentsRoute =
  AppAuthDashboardLayoutShipmentsRouteImport.update({
    id: '/shipments',
    path: '/shipments',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutExportRoute =
  AppAuthDashboardLayoutExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/free-tool': typeof FreeToolRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/terms-of-sale': typeof LegalTermsOfSaleRoute
  '/resources/eudr-checklist': typeof ResourcesEudrChecklistRoute
  '/resources/eudr-overview': typeof ResourcesEudrOverviewRoute
  '/resources/traceability-guide': typeof ResourcesTraceabilityGuideRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/export': typeof AppAuthDashboardLayoutExportRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/dashboard/shipments': typeof AppAuthDashboardLayoutShipmentsRoute
  '/onboarding/organization': typeof AppAuthOnboardingLayoutOrganizationRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-tool': typeof FreeToolRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/terms-of-sale': typeof LegalTermsOfSaleRoute
  '/resources/eudr-checklist': typeof ResourcesEudrChecklistRoute
  '/resources/eudr-overview': typeof ResourcesEudrOverviewRoute
  '/resources/traceability-guide': typeof ResourcesTraceabilityGuideRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/admin': typeof AdminIndexRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/export': typeof AppAuthDashboardLayoutExportRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/dashboard/shipments': typeof AppAuthDashboardLayoutShipmentsRoute
  '/onboarding/organization': typeof AppAuthOnboardingLayoutOrganizationRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/free-tool': typeof FreeToolRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/terms-of-sale': typeof LegalTermsOfSaleRoute
  '/resources/eudr-checklist': typeof ResourcesEudrChecklistRoute
  '/resources/eudr-overview': typeof ResourcesEudrOverviewRoute
  '/resources/traceability-guide': typeof ResourcesTraceabilityGuideRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/_app/_auth/dashboard/_layout/export': typeof AppAuthDashboardLayoutExportRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/dashboard/_layout/shipments': typeof AppAuthDashboardLayoutShipmentsRoute
  '/_app/_auth/onboarding/_layout/organization': typeof AppAuthOnboardingLayoutOrganizationRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/free-tool'
    | '/pricing'
    | '/resources'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/shipments'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/legal/dpa'
    | '/legal/notices'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/terms-of-sale'
    | '/resources/eudr-checklist'
    | '/resources/eudr-overview'
    | '/resources/traceability-guide'
    | '/supplier/$token'
    | '/admin/'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/login/'
    | '/dashboard/checkout'
    | '/dashboard/export'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/onboarding/organization'
    | '/dashboard/'
    | '/dashboard/settings/billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/free-tool'
    | '/pricing'
    | '/resources'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/shipments'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/legal/dpa'
    | '/legal/notices'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/terms-of-sale'
    | '/resources/eudr-checklist'
    | '/resources/eudr-overview'
    | '/resources/traceability-guide'
    | '/supplier/$token'
    | '/admin'
    | '/onboarding'
    | '/login'
    | '/dashboard/checkout'
    | '/dashboard/export'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/onboarding/organization'
    | '/dashboard'
    | '/dashboard/settings/billing'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/free-tool'
    | '/pricing'
    | '/resources'
    | '/_app/_auth'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/shipments'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/legal/dpa'
    | '/legal/notices'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/terms-of-sale'
    | '/resources/eudr-checklist'
    | '/resources/eudr-overview'
    | '/resources/traceability-guide'
    | '/supplier/$token'
    | '/admin/'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/checkout'
    | '/_app/_auth/dashboard/_layout/export'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/dashboard/_layout/shipments'
    | '/_app/_auth/onboarding/_layout/organization'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/dashboard/_layout/settings/billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  FreeToolRoute: typeof FreeToolRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  LegalDpaRoute: typeof LegalDpaRoute
  LegalNoticesRoute: typeof LegalNoticesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalTermsOfSaleRoute: typeof LegalTermsOfSaleRoute
  SupplierTokenRoute: typeof SupplierTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-tool': {
      id: '/free-tool'
      path: '/free-tool'
      fullPath: '/free-tool'
      preLoaderRoute: typeof FreeToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supplier/$token': {
      id: '/supplier/$token'
      path: '/supplier/$token'
      fullPath: '/supplier/$token'
      preLoaderRoute: typeof SupplierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/traceability-guide': {
      id: '/resources/traceability-guide'
      path: '/traceability-guide'
      fullPath: '/resources/traceability-guide'
      preLoaderRoute: typeof ResourcesTraceabilityGuideRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/eudr-overview': {
      id: '/resources/eudr-overview'
      path: '/eudr-overview'
      fullPath: '/resources/eudr-overview'
      preLoaderRoute: typeof ResourcesEudrOverviewRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/eudr-checklist': {
      id: '/resources/eudr-checklist'
      path: '/eudr-checklist'
      fullPath: '/resources/eudr-checklist'
      preLoaderRoute: typeof ResourcesEudrChecklistRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/legal/terms-of-sale': {
      id: '/legal/terms-of-sale'
      path: '/legal/terms-of-sale'
      fullPath: '/legal/terms-of-sale'
      preLoaderRoute: typeof LegalTermsOfSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/notices': {
      id: '/legal/notices'
      path: '/legal/notices'
      fullPath: '/legal/notices'
      preLoaderRoute: typeof LegalNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/organization': {
      id: '/_app/_auth/onboarding/_layout/organization'
      path: '/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof AppAuthOnboardingLayoutOrganizationRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/shipments': {
      id: '/_app/_auth/dashboard/_layout/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof AppAuthDashboardLayoutShipmentsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/export': {
      id: '/_app/_auth/dashboard/_layout/export'
      path: '/export'
      fullPath: '/dashboard/export'
      preLoaderRoute: typeof AppAuthDashboardLayoutExportRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
  }
}

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutCheckoutRoute: typeof AppAuthDashboardLayoutCheckoutRoute
  AppAuthDashboardLayoutExportRoute: typeof AppAuthDashboardLayoutExportRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutShipmentsRoute: typeof AppAuthDashboardLayoutShipmentsRoute
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutCheckoutRoute: AppAuthDashboardLayoutCheckoutRoute,
    AppAuthDashboardLayoutExportRoute: AppAuthDashboardLayoutExportRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutShipmentsRoute: AppAuthDashboardLayoutShipmentsRoute,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutOrganizationRoute: typeof AppAuthOnboardingLayoutOrganizationRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutOrganizationRoute:
      AppAuthOnboardingLayoutOrganizationRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResourcesRouteChildren {
  ResourcesEudrChecklistRoute: typeof ResourcesEudrChecklistRoute
  ResourcesEudrOverviewRoute: typeof ResourcesEudrOverviewRoute
  ResourcesTraceabilityGuideRoute: typeof ResourcesTraceabilityGuideRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesEudrChecklistRoute: ResourcesEudrChecklistRoute,
  ResourcesEudrOverviewRoute: ResourcesEudrOverviewRoute,
  ResourcesTraceabilityGuideRoute: ResourcesTraceabilityGuideRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  FreeToolRoute: FreeToolRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  LegalDpaRoute: LegalDpaRoute,
  LegalNoticesRoute: LegalNoticesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalTermsOfSaleRoute: LegalTermsOfSaleRoute,
  SupplierTokenRoute: SupplierTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
