/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierTokenRouteImport } from './routes/supplier/$token'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameRouteImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutShipmentsRouteImport } from './routes/_app/_auth/dashboard/_layout.shipments'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutRouteImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthDashboardLayoutSettingsBillingRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTokenRoute = SupplierTokenRouteImport.update({
  id: '/supplier/$token',
  path: '/supplier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/login/_layout',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthDashboardLayoutShipmentsRoute =
  AppAuthDashboardLayoutShipmentsRouteImport.update({
    id: '/shipments',
    path: '/shipments',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/dashboard/shipments': typeof AppAuthDashboardLayoutShipmentsRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/dashboard/shipments': typeof AppAuthDashboardLayoutShipmentsRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/supplier/$token': typeof SupplierTokenRoute
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/dashboard/_layout/shipments': typeof AppAuthDashboardLayoutShipmentsRoute
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/supplier/$token'
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/login/'
    | '/dashboard/checkout'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/onboarding/username'
    | '/dashboard/'
    | '/dashboard/settings/billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/supplier/$token'
    | '/onboarding'
    | '/login'
    | '/dashboard/checkout'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/onboarding/username'
    | '/dashboard'
    | '/dashboard/settings/billing'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/supplier/$token'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/checkout'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/dashboard/_layout/shipments'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/dashboard/_layout/settings/billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SupplierTokenRoute: typeof SupplierTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/$token': {
      id: '/supplier/$token'
      path: '/supplier/$token'
      fullPath: '/supplier/$token'
      preLoaderRoute: typeof SupplierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/shipments': {
      id: '/_app/_auth/dashboard/_layout/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof AppAuthDashboardLayoutShipmentsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
  }
}

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutCheckoutRoute: typeof AppAuthDashboardLayoutCheckoutRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutShipmentsRoute: typeof AppAuthDashboardLayoutShipmentsRoute
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutCheckoutRoute: AppAuthDashboardLayoutCheckoutRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutShipmentsRoute: AppAuthDashboardLayoutShipmentsRoute,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SupplierTokenRoute: SupplierTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
